---
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - jsx-a11y
  - import
rules:
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      arrowParens: "always"
      trailingComma: "all"
      printWidth: 160
  no-console: warn
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-unused-vars': [ 'error', {
    argsIgnorePattern: '^_',
    varsIgnorePattern: '^_',
    caughtErrorsIgnorePattern: '^_'
  } ]
  '@typescript-eslint/ban-ts-comment':
    - warn
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
      ts-nocheck: true
      ts-check: false
      minimumDescriptionLength: 5
  import/no-default-export: error
  import/extensions:
    - off
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  import/no-unresolved:
    - off
    - ignore:
        # For some reason this RegExp works only in yml config
        - '\?(url|raw)$'
        - geojson
#settings:
#  import/resolver:
#    alias:
#      map:
#        - [ '~', './src/' ]
#      extensions: [ '.ts', '.js', '.tsx' ]
